version: '3'
services:
  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    environment:
      API_URL: "http://localhost:3000/api/employees"

  backend:
    container_name: backend
    hostname: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      BASE_URL: http://localhost:4200
      MONGO_URI: mongodb://mongo/mean-crud
    depends_on:
      - mongo
      - frontend


  mongo:
    image: mongo:3.6-stretch
    restart: always
    ports:
<<<<<<< HEAD
      - 27017:27017
=======
      - 8080:8080

  web: 
    container_name: lab7
    build: .:/fronted/src/app'
      context:  '.:/fronted/src/app'
      dockerfile: Dockerfile
    volumes: 
      - '.:/fronted/src/app'
      - '/fronted/src/app/node_modules'
    ports: 
      - '4200:4200'
>>>>>>> a139bde0be133a7448fcb33eb22379043d476e8b
