version: "2.1"

services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080
        WebApp: 
          container_name: LAB7
          build: 
           context: .
          dockerfile: Dockerfile
    volumes: 
      - '.:/fronted/src/app'
      - '/fronted/src/app/node_modules'
    ports: 
      - '4200:4200'
    environment: 
      -  POSTGRES_PASSWORD: 123456
          POSTGRES_USER: ADMIN

