version: "2.1"

services: 
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080

  web: 
    container_name: lab7
    build: .:/fronted/src/app'
      context:  '.:/fronted/src/app'
      dockerfile: Dockerfile
    volumes: 
      - '.:/fronted/src/app'
      - '/fronted/src/app/node_modules'
    ports: 
      - '4200:4200'
